AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Resume Demo App DynamoDB Tables

  SAM Template for AWS

Parameters:
  Environment:
    Description: Environment
    Default: dev
    Type: String
    AllowedValues:
      - prod
      - test
      - dev
    ConstraintDescription: Must specify a valid environment dev, test or prod.

Mappings:
  ResumeMap:
    experiencesTable:
      name: resume_demo_experiences_web_app_table

Resources:
  ExperiencesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join ["_", [!FindInMap [ResumeMap, experiencesTable, name], !Ref 'Environment']]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: startDate
          AttributeType: S
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "type_startDate"
          KeySchema:
            - AttributeName: "type"
              KeyType: "HASH"
            - AttributeName: "startDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"

Outputs:
  ExperiencesTable:
    Description: "Experiences table"
    Value: !Ref ExperiencesTable
  ExperiencesTableArn:
    Description: "Experiences table ARN"
    Value: !GetAtt ExperiencesTable.Arn
